version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - aws --version
      - $(aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 539746929196.dkr.ecr.us-east-2.amazonaws.com)
  build:
    commands:
      - docker build -t test-app:latest .
  post_build:
    commands:
      - docker tag test-app:latest 539746929196.dkr.ecr.us-east-2.amazonaws.com/test-app:latest
      - docker push 539746929196.dkr.ecr.us-east-2.amazonaws.com/test-app:latest
      - echo Writing image definitions file...
      - printf '[{"name":"test-app-container","imageUri":"%s"}]' 539746929196.dkr.ecr.us-east-2.amazonaws.com/test-app:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json