version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-2)
      - echo checkout remote branch named $CODEBUILD_RESOLVED_SOURCE_VERSION
      - git checkout $CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - docker build -t cicd-test:latest .
      - docker tag cicd-test:latest 539746929196.dkr.ecr.us-east-2.amazonaws.com/cicd-test:latest
  post_build:
    commands:
      - docker push 539746929196.dkr.ecr.us-east-2.amazonaws.com/cicd-test:latest
      - echo Writing image definitions file...
      - printf '[{"name":"cicd-test-container","imageUri":"%s"}]' 539746929196.dkr.ecr.us-east-2.amazonaws.com/cicd-test:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json