version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-2)
  build:
    commands:
      - docker build -t cicd:latest .
      - docker tag cicd:latest 539746929196.dkr.ecr.us-east-2.amazonaws.com/cicd:latest
  post_build:
    commands:
      - docker push 539746929196.dkr.ecr.us-east-2.amazonaws.com/cicd:latest
      - echo Writing image definitions file...
      - printf '[{"name":"cicd-container","imageUri":"%s"}]' 539746929196.dkr.ecr.us-east-2.amazonaws.com/cicd:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json